double_metaphone_test_data = [
["X", "S", null],
["A", "A", null],
["E", "A", null],
["Y", "A", null],
["Ab", "AP", null],
["ALLERTON", "ALRT", null],
["Acton", "AKTN", null],
["Adams", "ATMS", null],
["Aggar", "AKR", null],
["Ahl", "AL", null],
["Aiken", "AKN", null],
["Alan", "ALN", null],
["Alcock", "ALKK", null],
["Alden", "ALTN", null],
["Aldham", "ALTM", null],
["Allen", "ALN", null],
["Allerton", "ALRT", null],
["Alsop", "ALSP", null],
["Alwein", "ALN", null],
["Ambler", "AMPL", null],
["Andevill", "ANTF", null],
["Andrews", "ANTR", null],
["Andreyco", "ANTR", null],
["Andriesse", "ANTR", null],
["Angier", "ANJ", "ANJR"],
["Annabel", "ANPL", null],
["Anne", "AN", null],
["Anstye", "ANST", null],
["Appling", "APLN", null],
["Apuke", "APK", null],
["Arnold", "ARNL", null],
["Ashby", "AXP", null],
["Astwood", "ASTT", null],
["Atkinson", "ATKN", null],
["Audley", "ATL", null],
["Austin", "ASTN", null],
["Avenal", "AFNL", null],
["Ayer", "AR", null],
["Ayot", "AT", null],
["Babbitt", "PPT", null],
["Bachelor", "PXLR", "PKLR"],
["Bachelour", "PXLR", "PKLR"],
["Bailey", "PL", null],
["Baivel", "PFL", null],
["Baker", "PKR", null],
["Baldwin", "PLTN", null],
["Balsley", "PLSL", null],
["Barber", "PRPR", null],
["Barker", "PRKR", null],
["Barlow", "PRL", "PRLF"],
["Barnard", "PRNR", null],
["Barnes", "PRNS", null],
["Barnsley", "PRNS", null],
["Barouxis", "PRKS", null],
["Bartlet", "PRTL", null],
["Basley", "PSL", null],
["Basset", "PST", null],
["Bassett", "PST", null],
["Batchlor", "PXLR", null],
["Bates", "PTS", null],
["Batson", "PTSN", null],
["Bayes", "PS", null],
["Bayley", "PL", null],
["Beale", "PL", null],
["Beauchamp", "PXMP", "PKMP"],
["Beauclerc", "PKLR", null],
["Beech", "PK", null],
["Beers", "PRS", null],
["Beke", "PK", null],
["Belcher", "PLXR", "PLKR"],
["Benjamin", "PNJM", null],
["Benningham", "PNNK", null],
["Bereford", "PRFR", null],
["Bergen", "PRJN", "PRKN"],
["Berkeley", "PRKL", null],
["Berry", "PR", null],
["Besse", "PS", null],
["Bessey", "PS", null],
["Bessiles", "PSLS", null],
["Bigelow", "PJL", "PKLF"],
["Bigg", "PK", null],
["Bigod", "PKT", null],
["Billings", "PLNK", null],
["Bimper", "PMPR", null],
["Binker", "PNKR", null],
["Birdsill", "PRTS", null],
["Bishop", "PXP", null],
["Black", "PLK", null],
["Blagge", "PLK", null],
["Blake", "PLK", null],
["Blanck", "PLNK", null],
["Bledsoe", "PLTS", null],
["Blennerhasset", "PLNR", null],
["Blessing", "PLSN", null],
["Blewett", "PLT", null],
["Bloctgoed", "PLKT", null],
["Bloetgoet", "PLTK", null],
["Bloodgood", "PLTK", null],
["Blossom", "PLSM", null],
["Blount", "PLNT", null],
["Bodine", "PTN", null],
["Bodman", "PTMN", null],
["BonCoeur", "PNKR", null],
["Bond", "PNT", null],
["Boscawen", "PSKN", null],
["Bosworth", "PSR0", "PSRT"],
["Bouchier", "PX", "PKR"],
["Bowne", "PN", null],
["Bradbury", "PRTP", null],
["Bradder", "PRTR", null],
["Bradford", "PRTF", null],
["Bradstreet", "PRTS", null],
["Braham", "PRHM", null],
["Brailsford", "PRLS", null],
["Brainard", "PRNR", null],
["Brandish", "PRNT", null],
["Braun", "PRN", null],
["Brecc", "PRK", null],
["Brent", "PRNT", null],
["Brenton", "PRNT", null],
["Briggs", "PRKS", null],
["Brigham", "PRM", null],
["Brobst", "PRPS", null],
["Brome", "PRM", null],
["Bronson", "PRNS", null],
["Brooks", "PRKS", null],
["Brouillard", "PRLR", null],
["Brown", "PRN", null],
["Browne", "PRN", null],
["Brownell", "PRNL", null],
["Bruley", "PRL", null],
["Bryant", "PRNT", null],
["Brzozowski", "PRSS", "PRTS"],
["Buide", "PT", null],
["Bulmer", "PLMR", null],
["Bunker", "PNKR", null],
["Burden", "PRTN", null],
["Burge", "PRJ", "PRK"],
["Burgoyne", "PRKN", null],
["Burke", "PRK", null],
["Burnett", "PRNT", null],
["Burpee", "PRP", null],
["Bursley", "PRSL", null],
["Burton", "PRTN", null],
["Bushnell", "PXNL", null],
["Buss", "PS", null],
["Buswell", "PSL", null],
["Butler", "PTLR", null],
["Calkin", "KLKN", null],
["Canada", "KNT", null],
["Canmore", "KNMR", null],
["Canney", "KN", null],
["Capet", "KPT", null],
["Card", "KRT", null],
["Carman", "KRMN", null],
["Carpenter", "KRPN", null],
["Cartwright", "KRTR", null],
["Casey", "KS", null],
["Catterfield", "KTRF", null],
["Ceeley", "SL", null],
["Chambers", "XMPR", null],
["Champion", "XMPN", null],
["Chapman", "XPMN", null],
["Chase", "XS", null],
["Cheney", "XN", null],
["Chetwynd", "XTNT", null],
["Chevalier", "XFL", "XFLR"],
["Chillingsworth", "XLNK", null],
["Christie", "KRST", null],
["Chubbuck", "XPK", null],
["Church", "XRX", "XRK"],
["Clark", "KLRK", null],
["Clarke", "KLRK", null],
["Cleare", "KLR", null],
["Clement", "KLMN", null],
["Clerke", "KLRK", null],
["Clibben", "KLPN", null],
["Clifford", "KLFR", null],
["Clivedon", "KLFT", null],
["Close", "KLS", null],
["Clothilde", "KL0L", "KLTL"],
["Cobb", "KP", null],
["Coburn", "KPRN", null],
["Coburne", "KPRN", null],
["Cocke", "KK", null],
["Coffin", "KFN", null],
["Coffyn", "KFN", null],
["Colborne", "KLPR", null],
["Colby", "KLP", null],
["Cole", "KL", null],
["Coleman", "KLMN", null],
["Collier", "KL", "KLR"],
["Compton", "KMPT", null],
["Cone", "KN", null],
["Cook", "KK", null],
["Cooke", "KK", null],
["Cooper", "KPR", null],
["Copperthwaite", "KPR0", "KPRT"],
["Corbet", "KRPT", null],
["Corell", "KRL", null],
["Corey", "KR", null],
["Corlies", "KRLS", null],
["Corneliszen", "KRNL", null],
["Cornelius", "KRNL", null],
["Cornwallis", "KRNL", null],
["Cosgrove", "KSKR", null],
["Count of Brionne", "KNTF", null],
["Covill", "KFL", null],
["Cowperthwaite", "KPR0", "KPRT"],
["Cowperwaite", "KPRT", null],
["Crane", "KRN", null],
["Creagmile", "KRKM", null],
["Crew", "KR", "KRF"],
["Crispin", "KRSP", null],
["Crocker", "KRKR", null],
["Crockett", "KRKT", null],
["Crosby", "KRSP", null],
["Crump", "KRMP", null],
["Cunningham", "KNNK", null],
["Curtis", "KRTS", null],
["Cutha", "K0", "KT"],
["Cutter", "KTR", null],
["D'Aubigny", "TPN", "TPKN"],
["DAVIS", "TFS", null],
["Dabinott", "TPNT", null],
["Dacre", "TKR", null],
["Daggett", "TKT", null],
["Danvers", "TNFR", null],
["Darcy", "TRS", null],
["Davis", "TFS", null],
["Dawn", "TN", null],
["Dawson", "TSN", null],
["Day", "T", null],
["Daye", "T", null],
["DeGrenier", "TKRN", null],
["Dean", "TN", null],
["Deekindaugh", "TKNT", null],
["Dennis", "TNS", null],
["Denny", "TN", null],
["Denton", "TNTN", null],
["Desborough", "TSPR", null],
["Despenser", "TSPN", null],
["Deverill", "TFRL", null],
["Devine", "TFN", null],
["Dexter", "TKST", null],
["Dillaway", "TL", null],
["Dimmick", "TMK", null],
["Dinan", "TNN", null],
["Dix", "TKS", null],
["Doggett", "TKT", null],
["Donahue", "TNH", null],
["Dorfman", "TRFM", null],
["Dorris", "TRS", null],
["Dow", "T", "TF"],
["Downey", "TN", null],
["Downing", "TNNK", null],
["Dowsett", "TST", null],
["Duck?", "TK", null],
["Dudley", "TTL", null],
["Duffy", "TF", null],
["Dunn", "TN", null],
["Dunsterville", "TNST", null],
["Durrant", "TRNT", null],
["Durrin", "TRN", null],
["Dustin", "TSTN", null],
["Duston", "TSTN", null],
["Eames", "AMS", null],
["Early", "ARL", null],
["Easty", "AST", null],
["Ebbett", "APT", null],
["Eberbach", "APRP", null],
["Eberhard", "APRR", null],
["Eddy", "AT", null],
["Edenden", "ATNT", null],
["Edwards", "ATRT", null],
["Eglinton", "AKLN", "ALNT"],
["Eliot", "ALT", null],
["Elizabeth", "ALSP", null],
["Ellis", "ALS", null],
["Ellison", "ALSN", null],
["Ellot", "ALT", null],
["Elny", "ALN", null],
["Elsner", "ALSN", null],
["Emerson", "AMRS", null],
["Empson", "AMPS", null],
["Est", "AST", null],
["Estabrook", "ASTP", null],
["Estes", "ASTS", null],
["Estey", "AST", null],
["Evans", "AFNS", null],
["Fallowell", "FLL", null],
["Farnsworth", "FRNS", null],
["Feake", "FK", null],
["Feke", "FK", null],
["Fellows", "FLS", null],
["Fettiplace", "FTPL", null],
["Finney", "FN", null],
["Fischer", "FXR", "FSKR"],
["Fisher", "FXR", null],
["Fisk", "FSK", null],
["Fiske", "FSK", null],
["Fletcher", "FLXR", null],
["Folger", "FLKR", "FLJR"],
["Foliot", "FLT", null],
["Folyot", "FLT", null],
["Fones", "FNS", null],
["Fordham", "FRTM", null],
["Forstner", "FRST", null],
["Fosten", "FSTN", null],
["Foster", "FSTR", null],
["Foulke", "FLK", null],
["Fowler", "FLR", null],
["Foxwell", "FKSL", null],
["Fraley", "FRL", null],
["Franceys", "FRNS", null],
["Franke", "FRNK", null],
["Frascella", "FRSL", null],
["Frazer", "FRSR", null],
["Fredd", "FRT", null],
["Freeman", "FRMN", null],
["French", "FRNX", "FRNK"],
["Freville", "FRFL", null],
["Frey", "FR", null],
["Frick", "FRK", null],
["Frier", "FR", "FRR"],
["Froe", "FR", null],
["Frorer", "FRRR", null],
["Frost", "FRST", null],
["Frothingham", "FR0N", "FRTN"],
["Fry", "FR", null],
["Gaffney", "KFN", null],
["Gage", "KJ", "KK"],
["Gallion", "KLN", null],
["Gallishan", "KLXN", null],
["Gamble", "KMPL", null],
["Garbrand", "KRPR", null],
["Gardner", "KRTN", null],
["Garrett", "KRT", null],
["Gassner", "KSNR", null],
["Gater", "KTR", null],
["Gaunt", "KNT", null],
["Gayer", "KR", null],
["Gerken", "KRKN", "JRKN"],
["Gerritsen", "KRTS", "JRTS"],
["Gibbs", "KPS", "JPS"],
["Giffard", "JFRT", "KFRT"],
["Gilbert", "KLPR", "JLPR"],
["Gill", "KL", "JL"],
["Gilman", "KLMN", "JLMN"],
["Glass", "KLS", null],
["Goddard\\Gifford", "KTRT", null],
["Godfrey", "KTFR", null],
["Godwin", "KTN", null],
["Goodale", "KTL", null],
["Goodnow", "KTN", "KTNF"],
["Gorham", "KRM", null],
["Goseline", "KSLN", null],
["Gott", "KT", null],
["Gould", "KLT", null],
["Grafton", "KRFT", null],
["Grant", "KRNT", null],
["Gray", "KR", null],
["Green", "KRN", null],
["Griffin", "KRFN", null],
["Grill", "KRL", null],
["Grim", "KRM", null],
["Grisgonelle", "KRSK", null],
["Gross", "KRS", null],
["Guba", "KP", null],
["Gybbes", "KPS", "JPS"],
["Haburne", "HPRN", null],
["Hackburne", "HKPR", null],
["Haddon?", "HTN", null],
["Haines", "HNS", null],
["Hale", "HL", null],
["Hall", "HL", null],
["Hallet", "HLT", null],
["Hallock", "HLK", null],
["Halstead", "HLST", null],
["Hammond", "HMNT", null],
["Hance", "HNS", null],
["Handy", "HNT", null],
["Hanson", "HNSN", null],
["Harasek", "HRSK", null],
["Harcourt", "HRKR", null],
["Hardy", "HRT", null],
["Harlock", "HRLK", null],
["Harris", "HRS", null],
["Hartley", "HRTL", null],
["Harvey", "HRF", null],
["Harvie", "HRF", null],
["Harwood", "HRT", null],
["Hathaway", "H0", "HT"],
["Haukeness", "HKNS", null],
["Hawkes", "HKS", null],
["Hawkhurst", "HKRS", null],
["Hawkins", "HKNS", null],
["Hawley", "HL", null],
["Heald", "HLT", null],
["Helsdon", "HLST", null],
["Hemenway", "HMN", null],
["Hemmenway", "HMN", null],
["Henck", "HNK", null],
["Henderson", "HNTR", null],
["Hendricks", "HNTR", null],
["Hersey", "HRS", null],
["Hewes", "HS", null],
["Heyman", "HMN", null],
["Hicks", "HKS", null],
["Hidden", "HTN", null],
["Higgs", "HKS", null],
["Hill", "HL", null],
["Hills", "HLS", null],
["Hinckley", "HNKL", null],
["Hipwell", "HPL", null],
["Hobart", "HPRT", null],
["Hoben", "HPN", null],
["Hoffmann", "HFMN", null],
["Hogan", "HKN", null],
["Holmes", "HLMS", null],
["Hoo", "H", null],
["Hooker", "HKR", null],
["Hopcott", "HPKT", null],
["Hopkins", "HPKN", null],
["Hopkinson", "HPKN", null],
["Hornsey", "HRNS", null],
["Houckgeest", "HKJS", "HKKS"],
["Hough", "H", null],
["Houstin", "HSTN", null],
["How", "H", "HF"],
["Howe", "H", null],
["Howland", "HLNT", null],
["Hubner", "HPNR", null],
["Hudnut", "HTNT", null],
["Hughes", "HS", null],
["Hull", "HL", null],
["Hulme", "HLM", null],
["Hume", "HM", null],
["Hundertumark", "HNTR", null],
["Hundley", "HNTL", null],
["Hungerford", "HNKR", "HNJR"],
["Hunt", "HNT", null],
["Hurst", "HRST", null],
["Husbands", "HSPN", null],
["Hussey", "HS", null],
["Husted", "HSTT", null],
["Hutchins", "HXNS", null],
["Hutchinson", "HXNS", null],
["Huttinger", "HTNK", "HTNJ"],
["Huybertsen", "HPRT", null],
["Iddenden", "ATNT", null],
["Ingraham", "ANKR", null],
["Ives", "AFS", null],
["Jackson", "JKSN", "AKSN"],
["Jacob", "JKP", "AKP"],
["Jans", "JNS", "ANS"],
["Jenkins", "JNKN", "ANKN"],
["Jewett", "JT", "AT"],
["Jewitt", "JT", "AT"],
["Johnson", "JNSN", "ANSN"],
["Jones", "JNS", "ANS"],
["Josephine", "JSFN", "HSFN"],
["Judd", "JT", "AT"],
["June", "JN", "AN"],
["Kamarowska", "KMRS", null],
["Kay", "K", null],
["Kelley", "KL", null],
["Kelly", "KL", null],
["Keymber", "KMPR", null],
["Keynes", "KNS", null],
["Kilham", "KLM", null],
["Kim", "KM", null],
["Kimball", "KMPL", null],
["King", "KNK", null],
["Kinsey", "KNS", null],
["Kirk", "KRK", null],
["Kirton", "KRTN", null],
["Kistler", "KSTL", null],
["Kitchen", "KXN", null],
["Kitson", "KTSN", null],
["Klett", "KLT", null],
["Kline", "KLN", null],
["Knapp", "NP", null],
["Knight", "NT", null],
["Knote", "NT", null],
["Knott", "NT", null],
["Knox", "NKS", null],
["Koeller", "KLR", null],
["La Pointe", "LPNT", null],
["LaPlante", "LPLN", null],
["Laimbeer", "LMPR", null],
["Lamb", "LMP", null],
["Lambertson", "LMPR", null],
["Lancto", "LNKT", null],
["Landry", "LNTR", null],
["Lane", "LN", null],
["Langendyck", "LNJN", "LNKN"],
["Langer", "LNKR", "LNJR"],
["Langford", "LNKF", null],
["Lantersee", "LNTR", null],
["Laquer", "LKR", null],
["Larkin", "LRKN", null],
["Latham", "LTM", null],
["Lathrop", "L0RP", "LTRP"],
["Lauter", "LTR", null],
["Lawrence", "LRNS", null],
["Leach", "LK", null],
["Leager", "LKR", "LJR"],
["Learned", "LRNT", null],
["Leavitt", "LFT", null],
["Lee", "L", null],
["Leete", "LT", null],
["Leggett", "LKT", null],
["Leland", "LLNT", null],
["Leonard", "LNRT", null],
["Lester", "LSTR", null],
["Lestrange", "LSTR", null],
["Lethem", "L0M", "LTM"],
["Levine", "LFN", null],
["Lewes", "LS", null],
["Lewis", "LS", null],
["Lincoln", "LNKL", null],
["Lindsey", "LNTS", null],
["Linher", "LNR", null],
["Lippet", "LPT", null],
["Lippincott", "LPNK", null],
["Lockwood", "LKT", null],
["Loines", "LNS", null],
["Lombard", "LMPR", null],
["Long", "LNK", null],
["Longespee", "LNJS", "LNKS"],
["Look", "LK", null],
["Lounsberry", "LNSP", null],
["Lounsbury", "LNSP", null],
["Louthe", "L0", "LT"],
["Loveyne", "LFN", null],
["Lowe", "L", null],
["Ludlam", "LTLM", null],
["Lumbard", "LMPR", null],
["Lund", "LNT", null],
["Luno", "LN", null],
["Lutz", "LTS", null],
["Lydia", "LT", null],
["Lynne", "LN", null],
["Lyon", "LN", null],
["MacAlpin", "MKLP", null],
["MacBricc", "MKPR", null],
["MacCrinan", "MKRN", null],
["MacKenneth", "MKN0", "MKNT"],
["MacMael nam Bo", "MKML", null],
["MacMurchada", "MKMR", null],
["Macomber", "MKMP", null],
["Macy", "MS", null],
["Magnus", "MNS", "MKNS"],
["Mahien", "MHN", null],
["Malmains", "MLMN", null],
["Malory", "MLR", null],
["Mancinelli", "MNSN", null],
["Mancini", "MNSN", null],
["Mann", "MN", null],
["Manning", "MNNK", null],
["Manter", "MNTR", null],
["Marion", "MRN", null],
["Marley", "MRL", null],
["Marmion", "MRMN", null],
["Marquart", "MRKR", null],
["Marsh", "MRX", null],
["Marshal", "MRXL", null],
["Marshall", "MRXL", null],
["Martel", "MRTL", null],
["Martha", "MR0", "MRT"],
["Martin", "MRTN", null],
["Marturano", "MRTR", null],
["Marvin", "MRFN", null],
["Mary", "MR", null],
["Mason", "MSN", null],
["Maxwell", "MKSL", null],
["Mayhew", "MH", "MHF"],
["McAllaster", "MKLS", null],
["McAllister", "MKLS", null],
["McConnell", "MKNL", null],
["McFarland", "MKFR", null],
["McIlroy", "MSLR", null],
["McNair", "MKNR", null],
["McNair-Landry", "MKNR", null],
["McRaven", "MKRF", null],
["Mead", "MT", null],
["Meade", "MT", null],
["Meck", "MK", null],
["Melton", "MLTN", null],
["Mendenhall", "MNTN", null],
["Mering", "MRNK", null],
["Merrick", "MRK", null],
["Merry", "MR", null],
["Mighill", "ML", null],
["Miller", "MLR", null],
["Milton", "MLTN", null],
["Mohun", "MHN", null],
["Montague", "MNTK", null],
["Montboucher", "MNTP", null],
["Moore", "MR", null],
["Morrel", "MRL", null],
["Morrill", "MRL", null],
["Morris", "MRS", null],
["Morton", "MRTN", null],
["Moton", "MTN", null],
["Muir", "MR", null],
["Mulferd", "MLFR", null],
["Mullins", "MLNS", null],
["Mulso", "MLS", null],
["Munger", "MNKR", "MNJR"],
["Munt", "MNT", null],
["Murchad", "MRXT", "MRKT"],
["Murdock", "MRTK", null],
["Murray", "MR", null],
["Muskett", "MSKT", null],
["Myers", "MRS", null],
["Myrick", "MRK", null],
["NORRIS", "NRS", null],
["Nayle", "NL", null],
["Newcomb", "NKMP", null],
["Newcomb(e)", "NKMP", null],
["Newkirk", "NKRK", null],
["Newton", "NTN", null],
["Niles", "NLS", null],
["Noble", "NPL", null],
["Noel", "NL", null],
["Northend", "NR0N", "NRTN"],
["Norton", "NRTN", null],
["Nutter", "NTR", null],
["Odding", "ATNK", null],
["Odenbaugh", "ATNP", null],
["Ogborn", "AKPR", null],
["Oppenheimer", "APNM", null],
["Otis", "ATS", null],
["Oviatt", "AFT", null],
["PRUST?", "PRST", null],
["Paddock", "PTK", null],
["Page", "PJ", "PK"],
["Paine", "PN", null],
["Paist", "PST", null],
["Palmer", "PLMR", null],
["Park", "PRK", null],
["Parker", "PRKR", null],
["Parkhurst", "PRKR", null],
["Parrat", "PRT", null],
["Parsons", "PRSN", null],
["Partridge", "PRTR", null],
["Pashley", "PXL", null],
["Pasley", "PSL", null],
["Patrick", "PTRK", null],
["Pattee", "PT", null],
["Patten", "PTN", null],
["Pawley", "PL", null],
["Payne", "PN", null],
["Peabody", "PPT", null],
["Peake", "PK", null],
["Pearson", "PRSN", null],
["Peat", "PT", null],
["Pedersen", "PTRS", null],
["Percy", "PRS", null],
["Perkins", "PRKN", null],
["Perrine", "PRN", null],
["Perry", "PR", null],
["Peson", "PSN", null],
["Peterson", "PTRS", null],
["Peyton", "PTN", null],
["Phinney", "FN", null],
["Pickard", "PKRT", null],
["Pierce", "PRS", null],
["Pierrepont", "PRPN", null],
["Pike", "PK", null],
["Pinkham", "PNKM", null],
["Pitman", "PTMN", null],
["Pitt", "PT", null],
["Pitts", "PTS", null],
["Plantagenet", "PLNT", null],
["Platt", "PLT", null],
["Platts", "PLTS", null],
["Pleis", "PLS", null],
["Pleiss", "PLS", null],
["Plisko", "PLSK", null],
["Pliskovitch", "PLSK", null],
["Plum", "PLM", null],
["Plume", "PLM", null],
["Poitou", "PT", null],
["Pomeroy", "PMR", null],
["Poretiers", "PRTR", null],
["Pote", "PT", null],
["Potter", "PTR", null],
["Potts", "PTS", null],
["Powell", "PL", null],
["Pratt", "PRT", null],
["Presbury", "PRSP", null],
["Priest", "PRST", null],
["Prindle", "PRNT", null],
["Prior", "PRR", null],
["Profumo", "PRFM", null],
["Purdy", "PRT", null],
["Purefoy", "PRF", null],
["Pury", "PR", null],
["Quinter", "KNTR", null],
["Rachel", "RXL", "RKL"],
["Rand", "RNT", null],
["Rankin", "RNKN", null],
["Ravenscroft", "RFNS", null],
["Raynsford", "RNSF", null],
["Reakirt", "RKRT", null],
["Reaves", "RFS", null],
["Reeves", "RFS", null],
["Reichert", "RXRT", "RKRT"],
["Remmele", "RML", null],
["Reynolds", "RNLT", null],
["Rhodes", "RTS", null],
["Richards", "RXRT", "RKRT"],
["Richardson", "RXRT", "RKRT"],
["Ring", "RNK", null],
["Roberts", "RPRT", null],
["Robertson", "RPRT", null],
["Robson", "RPSN", null],
["Rodie", "RT", null],
["Rody", "RT", null],
["Rogers", "RKRS", "RJRS"],
["Ross", "RS", null],
["Rosslevin", "RSLF", null],
["Rowland", "RLNT", null],
["Ruehl", "RL", null],
["Russell", "RSL", null],
["Ruth", "R0", "RT"],
["Ryan", "RN", null],
["Rysse", "RS", null],
["Sadler", "STLR", null],
["Salmon", "SLMN", null],
["Salter", "SLTR", null],
["Salvatore", "SLFT", null],
["Sanders", "SNTR", null],
["Sands", "SNTS", null],
["Sanford", "SNFR", null],
["Sanger", "SNKR", "SNJR"],
["Sargent", "SRJN", "SRKN"],
["Saunders", "SNTR", null],
["Schilling", "XLNK", null],
["Schlegel", "XLKL", "SLKL"],
["Scott", "SKT", null],
["Sears", "SRS", null],
["Segersall", "SJRS", "SKRS"],
["Senecal", "SNKL", null],
["Sergeaux", "SRJ", "SRK"],
["Severance", "SFRN", null],
["Sharp", "XRP", null],
["Sharpe", "XRP", null],
["Sharply", "XRPL", null],
["Shatswell", "XTSL", null],
["Shattack", "XTK", null],
["Shattock", "XTK", null],
["Shattuck", "XTK", null],
["Shaw", "X", "XF"],
["Sheldon", "XLTN", null],
["Sherman", "XRMN", null],
["Shinn", "XN", null],
["Shirford", "XRFR", null],
["Shirley", "XRL", null],
["Shively", "XFL", null],
["Shoemaker", "XMKR", null],
["Short", "XRT", null],
["Shotwell", "XTL", null],
["Shute", "XT", null],
["Sibley", "SPL", null],
["Silver", "SLFR", null],
["Simes", "SMS", null],
["Sinken", "SNKN", null],
["Sinn", "SN", null],
["Skelton", "SKLT", null],
["Skiffe", "SKF", null],
["Skotkonung", "SKTK", null],
["Slade", "SLT", "XLT"],
["Slye", "SL", "XL"],
["Smedley", "SMTL", "XMTL"],
["Smith", "SM0", "XMT"],
["Snow", "SN", "XNF"],
["Soole", "SL", null],
["Soule", "SL", null],
["Southworth", "S0R0", "STRT"],
["Sowles", "SLS", null],
["Spalding", "SPLT", null],
["Spark", "SPRK", null],
["Spencer", "SPNS", null],
["Sperry", "SPR", null],
["Spofford", "SPFR", null],
["Spooner", "SPNR", null],
["Sprague", "SPRK", null],
["Springer", "SPRN", null],
["St. Clair", "STKL", null],
["St. Claire", "STKL", null],
["St. Leger", "STLJ", "STLK"],
["St. Omer", "STMR", null],
["Stafferton", "STFR", null],
["Stafford", "STFR", null],
["Stalham", "STLM", null],
["Stanford", "STNF", null],
["Stanton", "STNT", null],
["Star", "STR", null],
["Starbuck", "STRP", null],
["Starkey", "STRK", null],
["Starkweather", "STRK", null],
["Stearns", "STRN", null],
["Stebbins", "STPN", null],
["Steele", "STL", null],
["Stephenson", "STFN", null],
["Stevens", "STFN", null],
["Stoddard", "STTR", null],
["Stodder", "STTR", null],
["Stone", "STN", null],
["Storey", "STR", null],
["Storrada", "STRT", null],
["Story", "STR", null],
["Stoughton", "STFT", null],
["Stout", "STT", null],
["Stow", "ST", "STF"],
["Strong", "STRN", null],
["Strutt", "STRT", null],
["Stryker", "STRK", null],
["Stuckeley", "STKL", null],
["Sturges", "STRJ", "STRK"],
["Sturgess", "STRJ", "STRK"],
["Sturgis", "STRJ", "STRK"],
["Suevain", "SFN", null],
["Sulyard", "SLRT", null],
["Sutton", "STN", null],
["Swain", "SN", "XN"],
["Swayne", "SN", "XN"],
["Swayze", "SS", "XTS"],
["Swift", "SFT", "XFT"],
["Taber", "TPR", null],
["Talcott", "TLKT", null],
["Tarne", "TRN", null],
["Tatum", "TTM", null],
["Taverner", "TFRN", null],
["Taylor", "TLR", null],
["Tenney", "TN", null],
["Thayer", "0R", "TR"],
["Thember", "0MPR", "TMPR"],
["Thomas", "TMS", null],
["Thompson", "TMPS", null],
["Thorne", "0RN", "TRN"],
["Thornycraft", "0RNK", "TRNK"],
["Threlkeld", "0RLK", "TRLK"],
["Throckmorton", "0RKM", "TRKM"],
["Thwaits", "0TS", "TTS"],
["Tibbetts", "TPTS", null],
["Tidd", "TT", null],
["Tierney", "TRN", null],
["Tilley", "TL", null],
["Tillieres", "TLRS", null],
["Tilly", "TL", null],
["Tisdale", "TSTL", null],
["Titus", "TTS", null],
["Tobey", "TP", null],
["Tooker", "TKR", null],
["Towle", "TL", null],
["Towne", "TN", null],
["Townsend", "TNSN", null],
["Treadway", "TRT", null],
["Trelawney", "TRLN", null],
["Trinder", "TRNT", null],
["Tripp", "TRP", null],
["Trippe", "TRP", null],
["Trott", "TRT", null],
["True", "TR", null],
["Trussebut", "TRSP", null],
["Tucker", "TKR", null],
["Turgeon", "TRJN", "TRKN"],
["Turner", "TRNR", null],
["Tuttle", "TTL", null],
["Tyler", "TLR", null],
["Tylle", "TL", null],
["Tyrrel", "TRL", null],
["Ua Tuathail", "AT0L", "ATTL"],
["Ulrich", "ALRX", "ALRK"],
["Underhill", "ANTR", null],
["Underwood", "ANTR", null],
["Unknown", "ANKN", null],
["Valentine", "FLNT", null],
["Van Egmond", "FNKM", null],
["Van der Beek", "FNTR", null],
["Vaughan", "FKN", null],
["Vermenlen", "FRMN", null],
["Vincent", "FNSN", null],
["Volentine", "FLNT", null],
["Wagner", "AKNR", "FKNR"],
["Waite", "AT", "FT"],
["Walker", "ALKR", "FLKR"],
["Walter", "ALTR", "FLTR"],
["Wandell", "ANTL", "FNTL"],
["Wandesford", "ANTS", "FNTS"],
["Warbleton", "ARPL", "FRPL"],
["Ward", "ART", "FRT"],
["Warde", "ART", "FRT"],
["Ware", "AR", "FR"],
["Wareham", "ARHM", "FRHM"],
["Warner", "ARNR", "FRNR"],
["Warren", "ARN", "FRN"],
["Washburne", "AXPR", "FXPR"],
["Waterbury", "ATRP", "FTRP"],
["Watson", "ATSN", "FTSN"],
["WatsonEllithorpe", "ATSN", "FTSN"],
["Watts", "ATS", "FTS"],
["Wayne", "AN", "FN"],
["Webb", "AP", "FP"],
["Weber", "APR", "FPR"],
["Webster", "APST", "FPST"],
["Weed", "AT", "FT"],
["Weeks", "AKS", "FKS"],
["Wells", "ALS", "FLS"],
["Wenzell", "ANSL", "FNTS"],
["West", "AST", "FST"],
["Westbury", "ASTP", "FSTP"],
["Whatlocke", "ATLK", null],
["Wheeler", "ALR", null],
["Whiston", "ASTN", null],
["White", "AT", null],
["Whitman", "ATMN", null],
["Whiton", "ATN", null],
["Whitson", "ATSN", null],
["Wickes", "AKS", "FKS"],
["Wilbur", "ALPR", "FLPR"],
["Wilcotes", "ALKT", "FLKT"],
["Wilkinson", "ALKN", "FLKN"],
["Willets", "ALTS", "FLTS"],
["Willett", "ALT", "FLT"],
["Willey", "AL", "FL"],
["Williams", "ALMS", "FLMS"],
["Williston", "ALST", "FLST"],
["Wilson", "ALSN", "FLSN"],
["Wimes", "AMS", "FMS"],
["Winch", "ANX", "FNK"],
["Winegar", "ANKR", "FNKR"],
["Wing", "ANK", "FNK"],
["Winsley", "ANSL", "FNSL"],
["Winslow", "ANSL", "FNSL"],
["Winthrop", "AN0R", "FNTR"],
["Wise", "AS", "FS"],
["Wood", "AT", "FT"],
["Woodbridge", "ATPR", "FTPR"],
["Woodward", "ATRT", "FTRT"],
["Wooley", "AL", "FL"],
["Woolley", "AL", "FL"],
["Worth", "AR0", "FRT"],
["Worthen", "AR0N", "FRTN"],
["Worthley", "AR0L", "FRTL"],
["Wright", "RT", null],
["Wyer", "AR", "FR"],
["Wyere", "AR", "FR"],
["Wynkoop", "ANKP", "FNKP"],
["Yarnall", "ARNL", null],
["Yeoman", "AMN", null],
["Yorke", "ARK", null],
["Young", "ANK", null],
["ab Wennonwen", "APNN", null],
["ap Llewellyn", "APLL", null],
["ap Lorwerth", "APLR", null],
["d'Angouleme", "TNKL", null],
["de Audeham", "TTHM", null],
["de Bavant", "TPFN", null],
["de Beauchamp", "TPXM", "TPKM"],
["de Beaumont", "TPMN", null],
["de Bolbec", "TPLP", null],
["de Braiose", "TPRS", null],
["de Braose", "TPRS", null],
["de Briwere", "TPRR", null],
["de Cantelou", "TKNT", null],
["de Cherelton", "TXRL", "TKRL"],
["de Cherleton", "TXRL", "TKRL"],
["de Clare", "TKLR", null],
["de Claremont", "TKLR", null],
["de Clifford", "TKLF", null],
["de Colville", "TKLF", null],
["de Courtenay", "TKRT", null],
["de Fauconberg", "TFKN", null],
["de Forest", "TFRS", null],
["de Gai", "TK", null],
["de Grey", "TKR", null],
["de Guernons", "TKRN", null],
["de Haia", "T", null],
["de Harcourt", "TRKR", null],
["de Hastings", "TSTN", null],
["de Hoke", "TK", null],
["de Hooch", "TK", null],
["de Hugelville", "TJLF", "TKLF"],
["de Huntingdon", "TNTN", null],
["de Insula", "TNSL", null],
["de Keynes", "TKNS", null],
["de Lacy", "TLS", null],
["de Lexington", "TLKS", null],
["de Lusignan", "TLSN", "TLSK"],
["de Manvers", "TMNF", null],
["de Montagu", "TMNT", null],
["de Montault", "TMNT", null],
["de Montfort", "TMNT", null],
["de Mortimer", "TMRT", null],
["de Morville", "TMRF", null],
["de Morvois", "TMRF", null],
["de Neufmarche", "TNFM", null],
["de Odingsells", "TTNK", null],
["de Odyngsells", "TTNK", null],
["de Percy", "TPRS", null],
["de Pierrepont", "TPRP", null],
["de Plessetis", "TPLS", null],
["de Porhoet", "TPRT", null],
["de Prouz", "TPRS", null],
["de Quincy", "TKNS", null],
["de Ripellis", "TRPL", null],
["de Ros", "TRS", null],
["de Salisbury", "TSLS", null],
["de Sanford", "TSNF", null],
["de Somery", "TSMR", null],
["de St. Hilary", "TSTL", null],
["de St. Liz", "TSTL", null],
["de Sutton", "TSTN", null],
["de Toeni", "TTN", null],
["de Tony", "TTN", null],
["de Umfreville", "TMFR", null],
["de Valognes", "TFLN", "TFLK"],
["de Vaux", "TF", null],
["de Vere", "TFR", null],
["de Vermandois", "TFRM", null],
["de Vernon", "TFRN", null],
["de Vexin", "TFKS", null],
["de Vitre", "TFTR", null],
["de Wandesford", "TNTS", null],
["de Warenne", "TRN", null],
["de Westbury", "TSTP", null],
["di Saluzzo", "TSLS", "TSLT"],
["fitz Alan", "FTSL", null],
["fitz Geoffrey", "FTSJ", "FTSK"],
["fitz Herbert", "FTSR", null],
["fitz John", "FTSJ", null],
["fitz Patrick", "FTSP", null],
["fitz Payn", "FTSP", null],
["fitz Piers", "FTSP", null],
["fitz Randolph", "FTSR", null],
["fitz Richard", "FTSR", null],
["fitz Robert", "FTSR", null],
["fitz Roy", "FTSR", null],
["fitz Scrob", "FTSS", null],
["fitz Walter", "FTSL", null],
["fitz Warin", "FTSR", null],
["fitz Williams", "FTSL", null],
["la Zouche", "LSX", "LSK"],
["le Botiller", "LPTL", null],
["le Despenser", "LTSP", null],
["le deSpencer", "LTSP", null],
["of Allendale", "AFLN", null],
["of Angouleme", "AFNK", null],
["of Anjou", "AFNJ", null],
["of Aquitaine", "AFKT", null],
["of Aumale", "AFML", null],
["of Bavaria", "AFPF", null],
["of Boulogne", "AFPL", null],
["of Brittany", "AFPR", null],
["of Brittary", "AFPR", null],
["of Castile", "AFKS", null],
["of Chester", "AFXS", "AFKS"],
["of Clermont", "AFKL", null],
["of Cologne", "AFKL", null],
["of Dinan", "AFTN", null],
["of Dunbar", "AFTN", null],
["of England", "AFNK", null],
["of Essex", "AFSK", null],
["of Falaise", "AFFL", null],
["of Flanders", "AFFL", null],
["of Galloway", "AFKL", null],
["of Germany", "AFKR", "AFJR"],
["of Gloucester", "AFKL", null],
["of Heristal", "AFRS", null],
["of Hungary", "AFNK", null],
["of Huntington", "AFNT", null],
["of Kiev", "AFKF", null],
["of Kuno", "AFKN", null],
["of Landen", "AFLN", null],
["of Laon", "AFLN", null],
["of Leinster", "AFLN", null],
["of Lens", "AFLN", null],
["of Lorraine", "AFLR", null],
["of Louvain", "AFLF", null],
["of Mercia", "AFMR", null],
["of Metz", "AFMT", null],
["of Meulan", "AFML", null],
["of Nass", "AFNS", null],
["of Normandy", "AFNR", null],
["of Ohningen", "AFNN", null],
["of Orleans", "AFRL", null],
["of Poitou", "AFPT", null],
["of Polotzk", "AFPL", null],
["of Provence", "AFPR", null],
["of Ringelheim", "AFRN", null],
["of Salisbury", "AFSL", null],
["of Saxony", "AFSK", null],
["of Scotland", "AFSK", null],
["of Senlis", "AFSN", null],
["of Stafford", "AFST", null],
["of Swabia", "AFSP", null],
["of Tongres", "AFTN", null],
["of the Tributes", "AF0T", "AFTT"],
["unknown", "ANKN", null],
["van der Gouda", "FNTR", null],
["von Adenbaugh", "FNTN", null],
["ARCHITure", "ARKT", null],
["Arnoff", "ARNF", null],
["Arnow", "ARN", "ARNF"],
["DANGER", "TNJR", "TNKR"],
["Jankelowicz", "JNKL", "ANKL"],
["MANGER", "MNJR", "MNKR"],
["McClellan", "MKLL", null],
["McHugh", "MK", null],
["McLaughlin", "MKLF", null],
["ORCHEStra", "ARKS", null],
["ORCHID", "ARKT", null],
["Pierce", "PRS", null],
["RANGER", "RNJR", "RNKR"],
["Schlesinger", "XLSN", "SLSN"],
["Uomo", "AM", null],
["Vasserman", "FSRM", null],
["Wasserman", "ASRM", "FSRM"],
["Womo", "AM", "FM"],
["Yankelovich", "ANKL", null],
["accede", "AKST", null],
["accident", "AKST", null],
["adelsheim", "ATLS", null],
["aged", "AJT", "AKT"],
["ageless", "AJLS", "AKLS"],
["agency", "AJNS", "AKNS"],
["aghast", "AKST", null],
["agio", "AJ", "AK"],
["agrimony", "AKRM", null],
["album", "ALPM", null],
["alcmene", "ALKM", null],
["alehouse", "ALHS", null],
["antique", "ANTK", null],
["artois", "ART", "ARTS"],
["automation", "ATMX", null],
["bacchus", "PKS", null],
["bacci", "PX", null],
["bajador", "PJTR", "PHTR"],
["bellocchio", "PLX", null],
["bertucci", "PRTX", null],
["biaggi", "PJ", "PK"],
["bough", "P", null],
["breaux", "PR", null],
["broughton", "PRTN", null],
["cabrillo", "KPRL", "KPR"],
["caesar", "SSR", null],
["cagney", "KKN", null],
["campbell", "KMPL", null],
["carlisle", "KRLL", null],
["carlysle", "KRLL", null],
["chemistry", "KMST", null],
["chianti", "KNT", null],
["chorus", "KRS", null],
["cough", "KF", null],
["czerny", "SRN", "XRN"],
["deffenbacher", "TFNP", null],
["dumb", "TM", null],
["edgar", "ATKR", null],
["edge", "AJ", null],
["filipowicz", "FLPT", "FLPF"],
["focaccia", "FKX", null],
["gallegos", "KLKS", "KKS"],
["gambrelli", "KMPR", null],
["geithain", "K0N", "JTN"],
["ghiradelli", "JRTL", null],
["ghislane", "JLN", null],
["gough", "KF", null],
["hartheim", "HR0M", "HRTM"],
["heimsheim", "HMSM", null],
["hochmeier", "HKMR", null],
["hugh", "H", null],
["hunger", "HNKR", "HNJR"],
["hungry", "HNKR", null],
["island", "ALNT", null],
["isle", "AL", null],
["jose", "HS", null],
["laugh", "LF", null],
["mac caffrey", "MKFR", null],
["mac gregor", "MKRK", null],
["pegnitz", "PNTS", "PKNT"],
["piskowitz", "PSKT", "PSKF"],
["queen", "KN", null],
["raspberry", "RSPR", null],
["resnais", "RSN", "RSNS"],
["rogier", "RJ", "RJR"],
["rough", "RF", null],
["san jacinto", "SNHS", null],
["schenker", "XNKR", "SKNK"],
["schermerhorn", "XRMR", "SKRM"],
["schmidt", "XMT", "SMT"],
["schneider", "XNTR", "SNTR"],
["school", "SKL", null],
["schooner", "SKNR", null],
["schrozberg", "XRSP", "SRSP"],
["schulman", "XLMN", null],
["schwabach", "XPK", "XFPK"],
["schwarzach", "XRSK", "XFRT"],
["smith", "SM0", "XMT"],
["snider", "SNTR", "XNTR"],
["succeed", "SKST", null],
["sugarcane", "XKRK", "SKRK"],
["svobodka", "SFPT", null],
["tagliaro", "TKLR", "TLR"],
["thames", "TMS", null],
["theilheim", "0LM", "TLM"],
["thomas", "TMS", null],
["thumb", "0M", "TM"],
["tichner", "TXNR", "TKNR"],
["tough", "TF", null],
["umbrella", "AMPR", null],
["vilshofen", "FLXF", null],
["von schuller", "FNXL", null],
["wachtler", "AKTL", "FKTL"],
["wechsler", "AKSL", "FKSL"],
["weikersheim", "AKRS", "FKRS"],
["zhao", "J", null]
];

Tinytest.add( "Double Metaphone Tests", function( test ) {
	_.each( double_metaphone_test_data, function( element, index, list ) {
		var input = element[0];
		var primary = element[1];
		var secondary = element[2];

		var result = TEXT_TOOLS.doubleMetaphone( input );
		test.equal( result, [primary, secondary], "item " + index + ", " + input );
	});
});